# Generated by Django 3.2 on 2021-04-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.specialite'),
        ),
    ]
