# Generated by Django 3.2 on 2021-04-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_alter_specialite_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('coeff', models.IntegerField(null=True)),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.specialite')),
            ],
        ),
    ]
