# Generated by Django 3.2 on 2021-04-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='titre',
            new_name='title',
        ),
    ]
