# Generated by Django 3.2 on 2021-04-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0005_alter_matiere_module'),
        ('specialite', '0001_initial'),
        ('etudiant', '0007_rename_titre_module_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialite.specialite'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
