# Generated by Django 3.2 on 2021-04-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0008_auto_20210427_2248'),
        ('etudiant', '0008_auto_20210427_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matieres',
            field=models.ManyToManyField(to='matiere.Matiere'),
        ),
    ]
