# Generated by Django 3.2 on 2021-04-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('ds', models.EmailField(max_length=100)),
                ('exam', models.CharField(max_length=100)),
                ('tp', models.CharField(max_length=100)),
                ('coeff', models.IntegerField(null=True)),
            ],
        ),
    ]
