# Generated by Django 3.2 on 2021-04-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='ds',
            field=models.CharField(max_length=100),
        ),
    ]
