# Generated by Django 3.2 on 2021-04-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_rename_titre_module_title'),
        ('matiere', '0002_alter_matiere_ds'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='Module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.module'),
        ),
    ]
