# Generated by Django 3.2 on 2021-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0005_alter_matiere_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='ds',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=100),
        ),
    ]
