# Generated by Django 3.2 on 2021-04-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matiere', '0008_auto_20210427_2248'),
        ('etudiant', '0009_user_matieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('note_ds', models.IntegerField()),
                ('note_exam', models.IntegerField()),
                ('note_tp', models.IntegerField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.user')),
            ],
        ),
    ]
