# Generated by Django 3.2 on 2021-04-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_note_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
